# Generated by Django 4.2.28 on 2026-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="ID чата в Telegram для уведомлений",
                max_length=100,
                null=True,
                verbose_name="Telegram chat ID",
            ),
        ),
    ]
