# Generated by Django 4.2.28 on 2026-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reminded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Время на выполнение привычки",
                verbose_name="Время на выполнение (сек)",
            ),
        ),
    ]
